name: Build Windows EXE

on:
  workflow_dispatch:      # Allows manual triggering in the Actions tab
  push:
    branches: [ main ]    # Or your default branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'     # Change if you need a different version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile main.py

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/main.exe
